### ISSUE TITLE
problem command Write file offset

### ISSUE THREAD

**Issue by marclabouille** [sparkfun/OpenLog#168]
Hi, i have tested the V3.3 for command write file offset, i want modify data on text, but when i enter the new data, the two Carriage return (exit write mode) killed the next data and i have a new line on my text
The V3.13 don't have this problem, i don't see the problem on code.

**Comment by nseidle** [comment]
I'm just scratching the surface of this issue. There are multiple things going on. Let's start with some test cases:

    new test.txt
    append test.txt
    1234567890<CR>^Z^Z^Z           //(should exit out)
    read test.txt 0 100 2                    //(show file from 0, 100 chars, in hex)
    output: 31 32 33 ... 39 30 D 1A 1A 1A          //0x0D is CR, 0x1A is ^Z

This output seems to be correct. I am using teraterm v4.87.

"The CR character 0x0D has been replaced with a LF 0x0A and then the 3 ^Z characters are written to the file."

This is perhaps a limit of your terminal program? I cannot replicate this problem.

"It's even worse when I use the write command to insert characters ABC at position 3."

Forgive me but there is too much going on in this issue to keep it straight. Please start another issue with specific test cases that I can test from a terminal. I really like your ideas about ways to avoid recording escape characters but there are some technical challenges to figure out.

**Comment by nseidle** [comment]
I believe most of the issues revolve around the write command. If we return to the original issue:

    rm test.txt
    new test.txt
    write test.txt
    123456789<enter><enter>
    read test.txt 0 100 2
    31 32 33 34 35 ... 39 A D       //A is NL, D is CR

It is odd that Openlog is recording a Newline and a carriage return

    write test.txt 1
    ABC<enter><enter>
    read test.txt 0 100 2
    31 41 42 43 A D 37 38 39 A D

This looks sort of correct. The NL and CR are being inserted the same as the previous write command. I believe the original poster wants the write command to not insert the 0x0A and 0x0D into the stream. This can be done but it will be tricky to not write two CRs but *to* write one CR followed by other text.

**Comment by jcdammeyer** [comment]
It’s been a few months since I looked at this.  I did a work-around.  I’ve almost used up the first 50 units.  I made 100 carrier boards for them so I’ll get getting another 50 or so.
 
Here’s the thing.  In DOS and before that in CP/M-80,  a ^Z marked the end of a text file.  If you opened the file and did a seek to the end to append to the file the next written character was written over the ^Z and the new text was terminated with the ^Z when the file was closed. 
You could have three ^Z characters there.  It doesn’t matter.
 
So a file might look like:
Hello World!<CR><LF> 
It’s a nice day outside. <CR><LF>
Do you want to Play? <CR><LF>^Z^Z^Z
 
Now if I want to append to the file the Line “No it’s cold outside.” The file would look like this.
 
Hello World!<CR><LF> 
It’s a nice day outside. <CR><LF>
Do you want to Play? <CR><LF>
No it’s cold outside. <CR><LF>^Z^Z^Z
 
IIRC, My testing showed the file looked like this.
Hello World!<CR><LF> 
It’s a nice day outside. <CR><LF>
Do you want to Play? <CR><LF>^Z^Z^Z
No it’s cold outside. <CR><LF>^Z^Z^Z
 
So instead I’d have to seek to the EOF minus 3 characters to get rid of the ^Z..  But then I’m not appending and the writing doesn’t terminate with the ^Z.  I think that’s what was happening.
 
But as I said, that’s a long time ago and the code for it is currently locked down and since it’s for a Homeland Security client I’m not allowed to just change it without the client doing extensive testing.
 
Thanks
John

**Comment by jcdammeyer** [comment]
Also to test what is written it's best to use write or append the data and close the file.  Then pull the MicroSD card ands mount it in your PC and load it with an editor that can look at the binary values.  That's when I discovered there were problems.  Writing and reading to the SD card in my application is done with a Delphi application and UART.  Not a terminal emulation program from the desktop.

**Comment by jcdammeyer** [comment]
![netclksd-backside](https://cloud.githubusercontent.com/assets/5903334/9392659/d8685ba8-4732-11e5-85c1-5f8a44da377c.jpg)I just checked the application code.
The solution was to break the file into smaller pieces.  I have one file per minute. So I'd rm the old one.  Append the new one and close it when done.  That solved the multiple ^Z issue since I never append to an existing file.  I have an #ifdef in the code for APPEND verses WRITE and APPEND is enabled.  
Simple solution for problem code.  The attached photo shows the board it's mounted on.  At the far back (not installed) is a WizNet Ethernet module.  On the bottom side of the board is a coin cell and RTC.  I have one version that runs ACN-E1.31 DMX-512A messaging on Ethernet and the plan was to also put show software on the SD card.
This board was done in a hurry because the client forgot to ask for it.  Then suddenly there was a deadline that had to be met.
A replacement

**Comment by nseidle** [comment]
So very cool! Thanks for posting the photo. Sounds like you've got some nice work arounds in place. 

To be clear, I'm not using an emulator - I am using a serial terminal to send commands directly to OpenLog. Teraterm is just a free/easy to use one that allows distinct CR/NL control.

The ^Z command is intended to drop the user to the command prompt, not to designate the end of a file (sorry for the confusion). The break command (^Z) on OpenLog is configurable to any ASCII character and was picked arbitrarily to be ^Z by me as the default. 

The write command relies on the user entering it from the command shell. This means it uses the read_line function which itself relies on searching for \r to signify the end of user input. 

    if(dataLen < (sizeof(buffer) - 1)) tempFile.write("\n\r", 2); //If we didn't fill up the buffer then user must have sent NL. Append new line and return

We could change the two bytes that are written to the file when using write command but I am worried about breaking compatibility with current users. 

I'm going to close this issue but open a new one that discusses methods to avoid recording the three escape characters from the log. I that feature would be more valuable than modifying how the write method works.

**Comment by JKPina** [comment]
Hi guys, I got #168 issue but I couldn't figure out if it was finally solved, I dived into the openlog firmware version 4, but checked that the piece of code referring to that issue was commented, so: is it a fixed issue or (even better) is a correct way in the uController code to avoid putting a <CR> in the file?

thanks in advance ;)

**Comment by jcdammeyer** [comment]
I don't know if it was ever fixed.  I ordered (and received) another 50 to finish off this production run.  Because the board these plug into uses an FTDI device that is only rated 0-70C and a -40C device isn't available in the package I'm using we will need to revise the main board for the next production run.  The OpenLog crystal is also only 0-70C and we don't want to rework it with a new crystal. 

That's a good enough excuse to fix some of the little issues and recreate the companion board to have a PIC32 for Ethernet, Battery backed up RTC and SD card support.  As I said above.  I worked around the issue and that interface code is stable.

**Comment by JKPina** [comment]
Finally I found that the best way to avoid escape characters ( `(<SUB>)` is just a particular escape character) in the end of file is just update the firmware to v4. as @nseidle said in another thread #196 https://github.com/sparkfun/OpenLog/issues/196

cheers,
