### ISSUE TITLE
Updating firmware through Arduino UNO

### ISSUE THREAD

**Issue by krevans** [sparkfun/OpenLog#181]
Is there a way to update the firmware through an Arduino UNO rather than purchasing the FTDI Basic and a crossover board?

**Comment by thenickdude** [comment]
It looks like you can remove the UNO from its socket, then basically take the breakout serial pins from your UNO and connect it to the OpenLog. Now when you upload the firmware you'll be talking to the OpenLog rather than the UNO:

http://www.instructables.com/id/Arduino-Examples-2-Use-an-Arduino-as-a-FTDI-Progr/

**Comment by krevans** [comment]
Thanks very much!
