### ISSUE TITLE
Pull up resistors on "NC" and "RSV" lines?

### ISSUE THREAD

**Issue by mhord** [sparkfun/OpenLog#201]
It's recommended (in several datasheets) that these lines be pulled up to VCC to reduce power consumption; these are CMOS data lines which are unused during SPI operation and they shouldn't be left floating. 

History suggests this isn't a problem, but best practice suggests otherwise.

**Comment by nseidle** [comment]
Nice find. I agree with what you're saying: pull up resistors are a safe thing for future SD based products. Since we haven't had a report of power problems over the past few years I am going to move ahead with this version of OpenLog and push this particular change on to a future revision. The firmware and power improvements on the current rev out-weight the time, labor, and risk costs.
